config/routes.rb
Basilica::Application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "users#new"
  resources :users
  resources :sessions
  resources :items
  
  get "/getuser/:name" => 'users#get_user_balance'
  post "/getuser/" => 'users#update'
  post "/updateitem/" => 'items#update'











end

app/models/item.rb
class Item
  include Mongoid::Document
  validates :item_id, :presence => true, :uniqueness => { :scope => :meta } 
  validates :meta, :presence => true
  attr_accessible :item_id, :meta, :name, :img_url, :quantity, :package, :value
  field :item_id, type: Integer
  field :meta, type: Integer
  field :name, type: String
  field :img_url, type: String
  field :quantity, type: Integer
  field :package, type: Integer
  field :value, type: Integer
end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword
  has_secure_password
  attr_accessible :name, :password, :password_confirmation, :balance
  validates :name, presence: true, uniqueness: true
  
  field :name, type: String
  field :password_digest, type: String
  field :balance, type: Integer
  
  class << self
    def find_by_name(name)
      if where(:name => /#{name}/i).exists?
        return where(:name => /#{name}/i).first
      else
        return nil
      end
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.where(:item_id => params[:item_id], :meta => params[:meta]).first

    if @item
      if (params[:quantity].to_i < 0) && @item.quantity >= @item.package
        if current_user && (current_user.balance < @item.value)
           redirect_to items_url, notice: "You can't afford any #{@item.name}."
        elsif current_user
          @item.update_attributes(:quantity => (@item.quantity + params[:quantity].to_i))
          user = User.find_by_name(current_user.name)
          user.update_attributes(:balance => (user.balance - @item.value))
          redirect_to items_url, notice: "You bought #{@item.name} x #{@item.package} for #{@item.value} credits."
        else
          @item.update_attributes(:quantity => (@item.quantity + params[:quantity].to_i))
          redirect_to items_url, notice: "Quantity of #{@item.name} decreased."
        end
      else
        @item.update_attributes(:quantity => (@item.quantity + params[:quantity].to_i))
        redirect_to items_url, notice: "Quantity of #{@item.name} increased."
      end
    else
      redirect_to items_url
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to items_url
    else
      flash.now.alert = "Invalid name or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # GET /users
  # GET /users.json
  def index
    #@users = User.order_by(:name.desc)
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  # GET /users/Wes
  # GET /users/Wes.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.find_by_name(params[:user][:name])
    if @user && @user.authenticate("initial")
      @user.update_attributes(password: params[:user][:password], 
                              password_confirmation: params[:user][:password_confirmation])
      respond_to do |format|
        if @user.save
          format.html { redirect_to "/log_in", notice: "User #{@user.name} 
          was successfully created." }
          format.json { render json: @user, status: :created, location: @user }
        else
          format.html { render action: "new" }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_url, notice: "User accounts must be created in-game first"
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.where(name: params[:name]).first

    respond_to do |format|
      if @user.update_attributes(balance: params[:balance])
        format.html { redirect_to users_url, notice: "User #{@user.name} 
        was successfully updated. Balance: #{@user.balance}" }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def get_user_balance
    if params[:name] =~ /^\D/
      @user = User.find_by_name(params[:name])
      if @user == nil
        @user = User.new(name: params[:name], balance: 5000,
                         password: "initial", password_confirmation: "initial")
      end
    else
      @user = User.find(params[:name])
    end

    respond_to do |format|
      if @user.save
        format.html # show.html.erb
        format.json { render json: "#{@user.balance}" }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item_id %><br />
    <%= f.number_field :item_id %>
  </div>
  <div class="field">
    <%= f.label :meta %><br />
    <%= f.number_field :meta %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :img_url %><br />
    <%= f.text_field :img_url %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :package %><br />
    <%= f.number_field :package %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.number_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<table>
  <tr>
  	<th colspan="6"><h1><%= Basilica %></h1></th>
  </tr>
  <tr>
  	<th>&nbsp;</th>
    <th>Item</th>
    <th>Quantity</th>
    <th>Package</th>
    <th>Cost</th>
    <th>&nbsp;</th>
  </tr>
<% @items.each do |item| %>
  <tr>
  	<td style="width:10%;"><%= image_tag(item.img_url, class: 'list_image') %></td>
    <td><%= item.name %></td>
    <td><%= item.quantity %></td>
    <td><%= item.package %></td>
    <td><%= item.value %></td>
    <td><%= button_to "Buy", { action: "update", :item_id => item.item_id, 
    	:meta => item.meta, :quantity => -1 * item.package, :method => :post} %></td>
  </tr>
<% end %>
</table>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Item:</b>
  <%= @item.item_id %>
</p>

<p>
  <b>Meta:</b>
  <%= @item.meta %>
</p>

<p>
  <b>Name:</b>
  <%= @item.name %>
</p>

<p>
  <b>Img url:</b>
  <%= @item.img_url %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Basilica</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
<div id="user_nav">
  <% if current_user %>
    Logged in as <%= current_user.name %>. Balance: <%= current_user.balance %>
    <%= link_to "Log out", log_out_path %>
  <% else %>
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "log in", log_in_path %>
  <% end %>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <fieldset>
  	<legend>Enter User Details</legend>
  	<div>
  		<%= f.label :name %>
  		<%= f.text_field :name, size: 40 %>
  	</div>
  	<div>
  		<%= f.label :password %>
  		<%= f.password_field :password, size: 40 %>
  	</div>
  	<div>
  		<%= f.label :password_confirmation, 'Confirm' %>
  		<%= f.password_field :password_confirmation, size: 40 %>
  	</div>
  	<div>
  		<%= f.submit %>
  	</div>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?',
    	method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @user.name %>
</p>

<p>
  <b>Balance:</b>
  <%= @user.balance %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>